language: android
android:
  components:
    - build-tools-18.1.0

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t android-16 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - ./wait_for_emulator

script: mvn install -Pintegration-tests -Dandroid.device=test
